### ISSUE TITLE
prime_number_multithreaded 빌드 실패 문제 

### ISSUE THREAD

**Issue by CactusJ** [imays76/GameServerBook#2]
안녕하세요.
예제 실행 중 빌드가 되지 않는 문제가 있어 해결방법은 찾았지만 
에러 발생 원인이 제 생각과 다르거나, 다른 분들이 동일한 문제를 겪었을 때 도움이 되지 않을까 싶어 이렇게 이슈를 남깁니다. 

환경 
    mac os 10.15.4
    visual studio code, g++ (c++ 11 옵션) 

에러나 나는 부분 
    shared_ptr<thread> thread(new **_thread_**([&]() {
    - error: must use 'class' tag to refer to type 'thread' in this scope
        shared_ptr<thread> thread(new thread([&]() {
원인 
   바로 앞에서 thread 객체 명을 thread로 선언해, new thread 시 thread라는 키워드를 바로 앞의 객체로 인식하는 문제 

해결
  shared_ptr<thread> **myThread**(new ~) 와 같이 객체의 이름을 변경해주는 것으로 해결

혹시나 잘못된 의견이라면 추가의견 부탁드립니다. 좋은 책 써주셔서 감사합니다.

**Comment by imays76** [comment]
안녕하세요,
C++ 컴파일러 특성상 컴파일에러가 나지 않을 법 한 부분인데, 에러가 난다니 좀 이상하네요.
의견주신것에 따라 수정하여 커밋했습니다.
제보 감사합니다.
